site_name: nRF Connect SDK Notes
site_url: https://tonyfu97.github.io/NrfConnectNotes/
site_description: Study Notes for nRF Connect SDK
site_author: Tony Fu

repo_url: https://github.com/tonyfu97/NrfConnectNotes
edit_uri: blob/master/docs/

theme:
    name: readthedocs
    locale: en
    analytics: {gtag: 'G-274394082'}
    highlightjs: true
    hljs_languages:
        - yaml
        - django
    features:
      - content.codehilite
      - content.code.copy

nav:
    - Home: index.md
    - Setup VSCode: setup-01-vscode.md
    - BLE-Minimal Skeleton: ble-01-minimal-skeleton.md
    - BLE-Advertising Simple: ble-02-advertising-simple.md
    - BLE-Advertising Connectable: ble-03-advert-connectable.md
    - BLE-Connection Parameters: ble-04-conn-params.md
    - BLE-GATT Client Operations: ble-05-gatt-client.md
    - BLE-GATT Server Operations: ble-06-gatt-server.md
    - BLE-Security Modes: ble-07-security-modes.md
    - BLE-Whitelisting: ble-08-whitelisting.md
    - NFC-Introduction: nfc-01-simple-text.md
    - NFC-Writable Tag: nfc-02-writable-tag.md
    - SDK-UART: sdk-01-uart.md
    - OS-Basic: os-01-basic.md
    - OS-Workqueue: os-02-workqueue.md

copyright: Copyright &copy; 2025 Tony Fu

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - pymdownx.arithmatex